<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="baas" nsURI="baas" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//UniqueElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositions" upperBound="-1"
        eType="#//Composition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifications" upperBound="-1"
        eType="#//Specification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//UniqueElement">
    <eOperations name="searchOperation" eType="#//DiscoveryResult">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addOperation">
      <eParameters name="operation" eType="#//Operation"/>
    </eOperations>
    <eOperations name="addMapping">
      <eParameters name="left" eType="#//IO"/>
      <eParameters name="right" eType="#//IO"/>
    </eOperations>
    <eOperations name="matchOperations" eType="#//IOMapping"/>
    <eOperations name="generate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specification" eSuperTypes="#//UniqueElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true" eOpposite="#//Operation/specification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rawSpecification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//UniqueElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ios" upperBound="-1" eType="#//IO"
        containment="true" eOpposite="#//IO/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" eType="#//Specification"
        eOpposite="#//Specification/operations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IO" eSuperTypes="#//UniqueElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"
        eOpposite="#//Operation/ios"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jsonPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datatype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticTypes" upperBound="-1"
        eType="#//SemanticType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" eType="#//SemanticType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#//SemanticType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="#//SemanticType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotator">
    <eOperations name="searchSemanticType" eType="#//AnnotationResult">
      <eParameters name="io" eType="#//IO"/>
    </eOperations>
    <eOperations name="add">
      <eParameters name="io" eType="#//IO"/>
      <eParameters name="type" eType="#//SemanticType"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationResult" eSuperTypes="#//Ranking"/>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscoveryResult" eSuperTypes="#//Ranking #//UniqueElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticTypeMapping" eSuperTypes="#//Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semantictype" eType="#//SemanticType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="io" eType="#//IO"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vector">
    <eOperations name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eOperations name="average" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="similarities" upperBound="-1"
        eType="#//Similarity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Similarity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sigma" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOMapping" eSuperTypes="#//Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vector" eType="#//Vector"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//IO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//IO"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping" abstract="true" interface="true"
      eSuperTypes="#//UniqueElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="confirmation" upperBound="-1"
        eType="#//Confirmation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relevance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="-1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ranking" abstract="true">
    <eOperations name="averagePrecision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="correct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//Mapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchingResult" eSuperTypes="#//Ranking"/>
  <eClassifiers xsi:type="ecore:EClass" name="Confirmation" eSuperTypes="#//UniqueElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datetime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationMapping" eSuperTypes="#//Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"/>
  </eClassifiers>
</ecore:EPackage>
